### ISSUE TITLE
/oauth/token raise 400 on server

### ISSUE THREAD

**Issue by sovanna** [lepture/example-oauth2-server#3]
the OAuth2 server raise a 400 status code while attempting to allow access from a client.

```
~> when I clicked on 'yes' formulair from url http://127.0.0.1:5000/oauth/authorize?response_type=code...etc
~> localhost:8000 throw an errror TypeError: sequence index must be integer, not 'str'
```

Indeed, the 'resp' is OAuthException

when I look at the log from the OAuth server, it responds to me with
{"error": "invalid_client"}', 400

While it doesn't work even if the id client, secret and so on are correct ?

I've try your example and my own implementation following your tutorial but I've got the same result, can you help me to figure out please!

thank you in advance

**Comment by Sphinxs** [comment]
I'm using Authlib 0.8 and I have the same problem :

```shell
(venv) ➜  api git:(master) curl -u ${g8VpLr1xzQ7WBankibygrDRO}:${xGPYloBxj5jRupJV3joYRanedPHriLwjFKfYkb2djMLMyIKT} -XPOST http://127.0.0.1:5000/oauth/token -F grant_type=password -F username=${admin} -F password=${123} -F scope=test

{"error": "invalid_client"}
```

**Comment by lepture** [comment]
@Sphinxs remove your `${}` in curl. This symbol is used to indicate that it is a variable.

**Comment by Sphinxs** [comment]
@lepture 

```shell
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "routes.py", line 167, in issue_token
    return authorization.create_token_response()

  File "venv/lib/python3.6/site-packages/authlib/flask/oauth2/authorization_server.py", line 251, in create_token_response
    AuthorizationServer, self).create_token_response(req)
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/authorization_server.py", line 162, in create_token_response
    grant.validate_token_request()
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/grants/resource_owner_password_credentials.py", line 89, in validate_token_request
    client = self.authenticate_token_endpoint_client()
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/grants/base.py", line 76, in authenticate_token_endpoint_client
    self.TOKEN_ENDPOINT_AUTH_METHODS
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/authenticate_client.py", line 51, in __call__
    return self.authenticate(request, methods)
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/authenticate_client.py", line 42, in authenticate
    client = func(self.query_client, request)
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/authenticate_client.py", line 60, in authenticate_client_secret_basic
    client = _validate_client(query_client, client_id, request.state, 401)
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/authenticate_client.py", line 120, in _validate_client
    client = query_client(client_id)
TypeError: 'NoneType' object is not callable
```

**Comment by Sphinxs** [comment]
@lepture I really appreciate your feedback, I fixed up and now I can get the token, thank you so much :satisfied:
